# Generated by Django 3.2.9 on 2023-04-25 11:40

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ellipse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='Компаний')),
                ('speakers', models.CharField(blank=True, max_length=16, null=True, verbose_name='Спикеров')),
                ('countries', models.CharField(blank=True, max_length=16, null=True, verbose_name='Стран')),
                ('panel_sessions', models.CharField(blank=True, max_length=16, null=True, verbose_name='Панельных сессий')),
                ('meetings', models.CharField(blank=True, max_length=16, null=True, verbose_name='B2B встречи')),
                ('exhibitors', models.CharField(blank=True, max_length=16, null=True, verbose_name='Экспонентов')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'ellipse',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок форма')),
                ('description', models.TextField(verbose_name='Описание форма')),
            ],
            options={
                'verbose_name': 'О форуме',
                'verbose_name_plural': 'О форуме',
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='PageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product', verbose_name='Фотография')),
                ('image_one', models.ImageField(upload_to='images/product', verbose_name='Фотография')),
                ('year', models.CharField(blank=True, max_length=8, null=True, verbose_name='Год')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок Экспо')),
                ('description', models.TextField(verbose_name='Описание Экспо')),
            ],
            options={
                'verbose_name': 'Начало',
                'verbose_name_plural': 'Начало',
                'db_table': 'page_one',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product', verbose_name='Фотография')),
                ('icon', models.ImageField(upload_to='images/product', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок сектора')),
                ('description', models.TextField(verbose_name='Описание сектора')),
            ],
            options={
                'verbose_name': 'Секторы',
                'verbose_name_plural': 'Секторы',
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок цели')),
                ('description', models.TextField(verbose_name='Описание цели')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'db_table': 'target',
            },
        ),
    ]
