# Generated by Django 3.2.9 on 2023-04-29 19:56

import apps.main_page.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_place_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название организации')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, validators=[apps.main_page.services.validate_file_extension], verbose_name='Фотография нашего организаторa *(157x127)')),
            ],
            options={
                'verbose_name': 'партнеров',
                'verbose_name_plural': 'Наши партнёры',
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название партнёра')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, validators=[apps.main_page.services.validate_file_extension], verbose_name='Логотип нашего партнёра *(157x127)')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партёры',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('snapchat', models.URLField(blank=True, null=True, verbose_name='Snapchat')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='Tiktok')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('wechat', models.URLField(blank=True, null=True, verbose_name='Wechat')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'socials',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография')),
                ('name', models.CharField(max_length=32, verbose_name='Полное имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'speakers',
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название спонсара')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, validators=[apps.main_page.services.validate_file_extension], verbose_name='Фотография нашего спонсара *(157x127)')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=128, verbose_name='Номер задач')),
                ('description', models.TextField(verbose_name='Описание задач')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, validators=[apps.main_page.services.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path),
        ),
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main_page.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pageone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pageone',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, validators=[apps.main_page.services.validate_file_extension], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография'),
        ),
    ]
