# Generated by Django 3.2.9 on 2023-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20230430_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='number',
            field=models.IntegerField(verbose_name='Номер задач'),
        ),
    ]
