# Generated by Django 3.2.9 on 2023-05-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20230430_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizers',
            options={'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.RemoveField(
            model_name='ellipse',
            name='panel_sessions',
        ),
        migrations.RemoveField(
            model_name='ellipse',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='pageone',
            name='image_one',
        ),
    ]
