# Generated by Django 3.2.9 on 2023-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_members_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
