# Generated by Django 3.2.9 on 2023-05-20 22:31

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_members_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('mail', models.URLField(blank=True, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
                'db_table': 'location_office',
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
