# Generated by Django 3.2.9 on 2023-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_en', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ApplicationEN',
        ),
    ]
