# Generated by Django 3.2.9 on 2023-05-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_en', '0003_auto_20230521_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeofficeen',
            options={'verbose_name': 'Локация офиса', 'verbose_name_plural': 'Локация офиса'},
        ),
    ]
